### ISSUE TITLE
Sad Button

### ISSUE THREAD

**Issue by janani2285** [lisbethmachado/project-1#10]
## USER STORY
AS a moody music lover, 
I WANT an application that provides me with music suggestions based on my mood. 
SO THAT I can better relate to my music choices.

## ACCEPTANCE CRITERIA
GIVEN user is at the home page
WHEN the “Sad” button is selected 
THEN the user is presented with suggestions of songs of “Linkin Park” that match their happy mood.

**Comment by lisbethduarte** [comment]
sad button display and function finished and commited.
